[package]
name = "patchbay-proto"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = ["vox"]
vox = []

[dependencies]
vox.workspace = true
vox-types.workspace = true
architect = { workspace = true, features = ["vox"] }
facet.workspace = true
serde.workspace = true
thiserror.workspace = true

[lib]
doctest = false

[lints]
workspace = true
