//! Live graph clock control via `pw-metadata` (same approach as
//! daw-audio-io's `pw` module: express intent, shell out, best-effort —
//! absent tools mean no-ops, no cfg needed).

use std::process::{Command, Stdio};

use patchbay_proto::ClockInfo;

fn quiet(program: &str) -> Command {
    let mut c = Command::new(program);
    c.stdout(Stdio::null()).stderr(Stdio::null());
    c
}

/// Force the graph quantum (frames, live); `0` clears the force.
pub fn force_quantum(frames: u32) {
    let _ = quiet("pw-metadata")
        .args([
            "-n",
            "settings",
            "0",
            "clock.force-quantum",
            &frames.to_string(),
        ])
        .status();
}

/// Read the live clock settings; zeroed when `pw-metadata` is missing.
pub fn clock_info() -> ClockInfo {
    let out = Command::new("pw-metadata")
        .args(["-n", "settings"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
        .unwrap_or_default();
    let mut c = ClockInfo::default();
    // Lines look like: update: id:0 key:'clock.rate' value:'48000' type:''
    for line in out.lines() {
        let Some((key, value)) = parse_metadata_line(line) else {
            continue;
        };
        let num = || value.parse::<u32>().unwrap_or(0);
        match key {
            "clock.rate" => c.rate = num(),
            "clock.quantum" => c.quantum = num(),
            "clock.force-quantum" => c.force_quantum = num(),
            "clock.force-rate" => c.force_rate = num(),
            "clock.min-quantum" => c.min_quantum = num(),
            "clock.max-quantum" => c.max_quantum = num(),
            _ => {}
        }
    }
    c
}

// ── Clock-defaults drop-in (runtime version of 50-quantum.conf) ─────────

use std::path::PathBuf;

use patchbay_proto::ClockDefaults;

fn defaults_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("pipewire/pipewire.conf.d/99-fts-patchbay-clock.conf")
}

/// Read back the patchbay-owned drop-in (zeros when absent).
pub fn clock_defaults() -> ClockDefaults {
    let text = std::fs::read_to_string(defaults_path()).unwrap_or_default();
    let field = |key: &str| {
        text.lines()
            .find_map(|l| {
                let l = l.trim();
                l.strip_prefix(key)
                    .and_then(|r| r.trim_start().strip_prefix('='))
            })
            .and_then(|v| v.trim().parse().ok())
            .unwrap_or(0)
    };
    ClockDefaults {
        quantum: field("default.clock.quantum"),
        min_quantum: field("default.clock.min-quantum"),
        max_quantum: field("default.clock.max-quantum"),
    }
}

/// Write (all-zero = delete) the drop-in. Later filenames win over the
/// flake's `50-quantum.conf`, so this overrides declarative defaults
/// without a nixos rebuild. Applies on PipeWire restart.
pub fn set_clock_defaults(d: ClockDefaults) -> Result<(), String> {
    let path = defaults_path();
    if d == ClockDefaults::default() {
        if path.exists() {
            std::fs::remove_file(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        }
        return Ok(());
    }
    let mut body = String::from(
        "# Generated by FTS Patchbay — runtime clock defaults (overrides\n\
         # the flake's 50-quantum.conf; restart PipeWire to apply).\n\
         context.properties = {\n",
    );
    let mut push = |key: &str, v: u32| {
        if v != 0 {
            body.push_str(&format!("    {key} = {v}\n"));
        }
    };
    push("default.clock.quantum", d.quantum);
    push("default.clock.min-quantum", d.min_quantum);
    push("default.clock.max-quantum", d.max_quantum);
    body.push_str("}\n");
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    std::fs::write(&path, body).map_err(|e| format!("{}: {e}", path.display()))
}

/// Pull `key:'…' value:'…'` out of a pw-metadata line.
fn parse_metadata_line(line: &str) -> Option<(&str, &str)> {
    let key_start = line.find("key:'")? + 5;
    let key_end = key_start + line[key_start..].find('\'')?;
    let val_start = line.find("value:'")? + 7;
    let val_end = val_start + line[val_start..].find('\'')?;
    Some((&line[key_start..key_end], &line[val_start..val_end]))
}
