//! Per-app latency rules → a WirePlumber drop-in.
//!
//! Rules live in the patchbay config (source of truth) and are
//! materialized to
//! `~/.config/wireplumber/wireplumber.conf.d/99-fts-patchbay-latency.conf`
//! as `node.rules` entries. WirePlumber applies props when it creates a
//! node, so changes take effect on app restart — or immediately for
//! everything via a WirePlumber restart (the services panel button).

use std::fs;
use std::path::PathBuf;

use patchbay_proto::LatencyRule;

fn dropin_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("wireplumber/wireplumber.conf.d/99-fts-patchbay-latency.conf")
}

/// Serialize the rules as SPA-JSON `node.rules`. `rate` is the graph
/// rate for the `node.latency` fraction (48000 fallback).
fn render(rules: &[LatencyRule], rate: u32) -> String {
    let rate = if rate == 0 { 48000 } else { rate };
    let mut out = String::from(
        "# Generated by FTS Patchbay — edit rules in the app, not here.\n\
         # Per-app latency: node.latency is a request (driver runs at the\n\
         # minimum among running nodes); node.force-quantum is a hard pin\n\
         # while the node is active.\n\
         node.rules = [\n",
    );
    for rule in rules {
        // WirePlumber match syntax passes through: `~` prefix = regex.
        // Escape quotes so a weird node name can't break the file.
        let pattern = rule.pattern.replace('"', "\\\"");
        out.push_str(&format!(
            "  {{\n    matches = [\n      {{ node.name = \"{pattern}\" }}\n    ]\n    actions = {{\n      update-props = {{\n"
        ));
        if rule.force {
            out.push_str(&format!("        node.force-quantum = {}\n", rule.quantum));
        }
        out.push_str(&format!(
            "        node.latency = \"{}/{}\"\n      }}\n    }}\n  }}\n",
            rule.quantum, rate
        ));
    }
    out.push_str("]\n");
    out
}

/// Write (or remove, when empty) the drop-in for `rules`.
pub(crate) fn write_dropin(rules: &[LatencyRule], rate: u32) -> Result<(), String> {
    let path = dropin_path();
    if rules.is_empty() {
        if path.exists() {
            fs::remove_file(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        }
        return Ok(());
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    fs::write(&path, render(rules, rate)).map_err(|e| format!("{}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_request_and_pin() {
        let rules = vec![
            LatencyRule {
                pattern: "REAPER".into(),
                quantum: 64,
                force: true,
            },
            LatencyRule {
                pattern: "~Firefox.*".into(),
                quantum: 1024,
                force: false,
            },
        ];
        let text = render(&rules, 48000);
        assert!(text.contains("node.name = \"REAPER\""));
        assert!(text.contains("node.force-quantum = 64"));
        assert!(text.contains("node.latency = \"64/48000\""));
        assert!(text.contains("node.name = \"~Firefox.*\""));
        assert!(!text.contains("node.force-quantum = 1024"));
        assert!(text.contains("node.latency = \"1024/48000\""));
    }
}
